title: Ji Hae Choi
position: Ph.D. Student
affiliation: Northwestern University
email: jihae [dot] choi (at) kellogg.northwestern.edu
$google_scholar: https://scholar.google.com/
github_link: https://github.com/JiHaeChoi
linkedin: https://www.linkedin.com/in/jihaechoi/
cv_link: ./assets/CV_JHC_092325.pdf
avatar: ./assets/img/profile.png
#google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Computational Social Scientist at Business School
#canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
