title: Ji Hae Choi
position: Ph.D. Student
affiliation: Northwestern Universit
location: Chicago, USA (GMT-5)
email: jihae [dot] choi (at) kellogg.northwestern.edu
#google_scholar: https://scholar.google.com/
github_link: https://github.com/JiHaeChoi
linkedin: https://www.linkedin.com/in/jihaechoi/
cv_link: ./assets/CV_JHC_092425.pdf
avatar: ./assets/img/profile.jpg
google_analytics: G-ZHV05533VK
favicon: ./assets/img/rainbow.png
favicon_dark: ./assets/img/rainbow.png
description: Computational Social Scientist at Business School
#canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
